enum ORDER_PURCHASE_STATUS {
  CANCEL = "CANCEL",
  ORDER = "ORDER",
  TRADING = "TRADING",
  DONE = "DONE",
}
enum ORDER_IMPORT_STATUS {
  CANCEL = "CANCEL",
  TRADING = "TRADING",
  DONE = "DONE",
}
enum ORDER_RESULT_STATUS {
  SUCCESS = "SUCCESS",
  FAIL = "FAIL",
}
export { ORDER_PURCHASE_STATUS, ORDER_RESULT_STATUS, ORDER_IMPORT_STATUS };
